pipeline {
    agent any

    environment {
        AWS_REGION = 'us-west-1'  // Update with your region
        ECR_REPOSITORY = 'chandu/my-docker-repo' // Update ECR Repo
        IMAGE_TAG = "latest"
        S3_BUCKET = "my-output-bucket" // Update with your S3 bucket name
    }

    stages {
        stage('Checkout Code') {
            steps {
                https://github.com/PolojuPoornachandar/Docker-Zero-to-Hero/examples/first-docker-file/.git/'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $ECR_REPOSITORY:$IMAGE_TAG examples/'
                }
            }
        }

        stage('Push to ECR') {
            steps {
                script {
                    sh """
                        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 116981807202.dkr.ecr.$AWS_REGION.amazonaws.com
                        docker tag $ECR_REPOSITORY:$IMAGE_TAG 116981807202.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
                        docker push 116981807202.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
                    """
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run --name my-container -d $ECR_REPOSITORY:$IMAGE_TAG'
                }
            }
        }

        stage('Test Application & Capture Output') {
            steps {
                script {
                    sh 'docker logs my-container > hello-world.txt'
                }
            }
        }

        stage('Upload Output to S3') {
            steps {
                script {
                    sh 'aws s3 cp hello-world.txt s3://$S3_BUCKET/'
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully!"
        }
        failure {
            echo "Pipeline failed! Check logs."
        }
    }
}
